name: Validate

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    name: Validate with HACS Action
    steps:
      - name: 🏗️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔍 HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: themes brands

  validate-hassfest:
    runs-on: ubuntu-latest
    name: Validate with Hassfest
    steps:
      - name: 🏗️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔍 Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Checks
    steps:
      - name: 🏗️ Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy
          pip install -r tests/requirements.txt

      - name: 🎨 Check code formatting with Black
        run: black --check --diff custom_components/

      - name: 📚 Check import sorting with isort
        run: isort --check-only --diff custom_components/

      - name: 🔍 Lint with flake8
        run: flake8 custom_components/ --max-line-length=100 --ignore=E203,W503

      - name: 🔍 Type checking with mypy
        run: mypy custom_components/ --ignore-missing-imports --no-strict-optional

  test-integration:
    runs-on: ubuntu-latest
    name: Run Integration Tests
    steps:
      - name: 🏗️ Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install 'balena-sdk>=15.0.0'

      - name: 🧪 Run tests
        run: |
          cd tests
          python test_runner.py

      - name: 📊 Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/
