name: Validate

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    name: Validate with HACS Action
    steps:
      - name: 🏗️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔍 HACS validation
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    runs-on: ubuntu-latest
    name: Validate with Hassfest
    steps:
      - name: 🏗️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔍 Hassfest validation
        uses: home-assistant/actions/hassfest@master

  test-integration:
    runs-on: ubuntu-latest
    name: Run Integration Tests
    steps:
      - name: 🏗️ Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install 'balena-sdk>=15.0.0'

      - name: 🧪 Run tests
        run: |
          cd tests
          python test_runner.py

      - name: 📊 Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/
